parameters:
#    intrix_frontend.example.class: Intrix\FrontendBundle\Example

services:
#    intrix_frontend.example:
#        class: %intrix_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
